spring:
  application:
    name: contas-termometro-project
  profiles:
    default: local

server:
  port: ${SERVER_PORT:17321}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  environment: ${APP_ENV:local}
  firebase:
    project-id: ${FIREBASE_PROJECT_ID:}

